# These are supported funding model platforms

github: [GokhanKR]
patreon: GokhanKR
open_collective: gokhan-korul
ko_fi: gokhankr
liberapay: GokhanKR
issuehunt: GokhanKR
polar: GokhanKR
buy_me_a_coffee: gokhankr
